name: Integration Linux

on:
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:

  linux:
    name: Linux
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Install Go
        uses: actions/setup-go@v6
        with:
          go-version-file: go.mod

      - name: Restore Kronk cache
        id: cache-kronk
        uses: actions/cache/restore@v5
        with:
          path: ~/.locallens/kronk
          key: Linux-kronk-b9247-v1

      - name: Setup LocalLens dependencies
        if: steps.cache-kronk.outputs.cache-hit != 'true'
        env:
          CGO_ENABLED: 0
          KRONK_PROCESSOR: cpu
        run: go run ./cmd/setup/

      - name: Save Kronk cache
        if: steps.cache-kronk.outputs.cache-hit != 'true'
        uses: actions/cache/save@v5
        with:
          path: ~/.locallens/kronk
          key: Linux-kronk-b9247-v1

      - name: Run service tests
        env:
          CGO_ENABLED: 0
          KRONK_PROCESSOR: cpu
        run: go test -tags "integration" -timeout 30m -v -count=1 ./internal/service/tests
